# Generated by Django 4.2.5 on 2023-11-19 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approval_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('workflow_id', models.AutoField(primary_key=True, serialize=False)),
                ('workflow_name', models.CharField(max_length=255)),
                ('trigger_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('users_in_sequence', models.ManyToManyField(to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=200)),
                ('headers', models.CharField(max_length=63)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.approvalrequest')),
            ],
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='api.userprofile'),
        ),
    ]
