# Generated by Django 4.2.5 on 2023-11-20 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalrequest',
            name='approval_value',
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='workflow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approval_requests', to='api.workflow'),
        ),
        migrations.CreateModel(
            name='ApprovalRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='records', to='api.approvalrequest')),
                ('current_approver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approvals', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.approvalrequest')),
            ],
        ),
    ]
