# Generated by Django 4.2.5 on 2023-11-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_approvalrequest_approval_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrecords',
            name='order',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
