# Generated by Django 4.2.5 on 2023-11-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_approvalrecords_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrecords',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
